name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-y-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Angular 16 soporta Node 16 y 18
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Tests unitarios
        run: npx ng test --watch=false --browsers=ChromeHeadless

      - name: Build de producción
        run: npx ng build --configuration production
